language: python
python:
  - "2.7"
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install pip --upgrade
# RDFLib requres html5lib;  html5lib requires setuptools version 18.5 or above;
  - pip install setuptools==25.1.0
  - python setup.py sdist
  - pip install dist/ga4gh*.tar.gz
# every installable in setup.py's entry_points should be tested here
  - ga4gh_client --version
  - ga4gh_configtest --version
  - ga4gh_server --version
  - ga2vcf --version
  - ga2sam --version
  - ga4gh_repo --version

before_script:
  # the following two lines are to prevent travis from
  # verbosely complaining about a security problem; see issue 54
  - mkdir $HOME/.python-eggs
  - chmod og-w $HOME/.python-eggs
  - pip install -r dev-requirements.txt
  - python scripts/build_test_data.py 


# run_tests.py runs everything under the script: tag so only put commands
# under it that we want to run (and want to be able to run) as local tests
script: 
  - flake8 *.py tests ga4gh scripts
              --exclude=ez_setup.py,ga4gh/*_pb2.py,ga4gh/datamodel/obo_parser.py
  - nosetests --with-coverage --cover-package ga4gh
              --cover-inclusive --cover-min-percentage 80
              --cover-branches --cover-erase
  - make clean -C docs
  - make -C docs
